name: Odoo Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Odoo Tests
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "123"
          POSTGRES_DB: project_ci_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: "123"
      VERSION: "15.0"
      ODOO_BRANCH: "15.0"
      ODOO_REPO: "odoo/odoo"
      LINT_CHECK: "0"
      TESTS: "1"
      CODECOV_TOKEN: "3e5036d1-b936-42c3-8599-fb5ceb73780a"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove -y nodejs libnode72
          sudo apt-get install -y postgresql-client expect-dev python3-dev python3-pip build-essential \
            libsasl2-dev libldap2-dev libssl-dev libxml2-dev libxmlsec1-dev libxslt-dev \
            libfontconfig1 libfreetype6 xvfb

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install coverage coveralls codecov six
          # pip install -r requirements.txt

      - name: Clone OCA maintainer-quality-tools
        run: |
          git clone https://github.com/OCA/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools

      - name: Export OCA Tools Path
        run: |
          echo "${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools" >> $GITHUB_PATH

      - name: Install PhantomJS properly
        run: |
          # Configuração definitiva do PhantomJS
          export PHANTOMJS_CDNURL=https://bitbucket.org/ariya/phantomjs/downloads
          npm install -g phantomjs-prebuilt@2.1.16 --unsafe-perm --prefix ~/.npm-global
          echo "export PATH=$HOME/.npm-global/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
          phantomjs --version

      - name: Run Odoo Tests
        run: |
          # Configura ambiente virtual para testes
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          travis_install_nightly || echo "Ignoring travis_install_nightly warnings"
          travis_run_tests
          travis_after_tests_success || true

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
